name: CI

on:
  push: 
    paths:
      - src/**
    branches: 
      - feature-branch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Shorten commit id
        shell: bash
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: strrst30/python-app:${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Install ArgoCD CLI
        run: |
             curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 
             chmod +x argocd
             sudo mv ./argocd /usr/local/bin/argocd
      - name: ArgoCD Login
        run: |
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password "${{ secrets.ARGOCD_ADMIN_PASSWORD }}"

      - name: Sync ArgoCD App
        run: |
          argocd app sync python-app
