name: CI

on:
  push: 
    paths:
      - src/**
    branches: 
      - feature-branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: shorten commit id
         shell: bash
         run: |
           echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
           

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: strrst30/python-app:${{ env.COMMIT_ID }}
